### ISSUE TITLE
Chestplate Model NBT

### ISSUE THREAD

**Issue by yungando** [mrmelon54/armored-elytra-fabric#1]
Currently the Elytra's texture changes correctly when using mods that alter textures based on NBT data (ItemNBTModels) or name changes (Optifine's CIT), but the Chestplate always uses the default texture even if it would otherwise use a custom texture when not combined. I assume this is because it just returns the Chestplate type but none of the data.

Since all the Chestplate's NBT data is saved within the Elytra when it's combined, is there any way the NBT data can be passed in when rendering the physical Chestplate?

If this is possible, it should also work with any future development Mojang puts into Custom Model Texture overrides.

**Comment by mrmelon54** [comment]
I can fix that if you want. Currently only the color property of leather chestplates is used when forcing the chestplate to render.

**Comment by yungando** [comment]
That would be perfect

**Comment by mrmelon54** [comment]
Not quite sure how I could do that yet but I'll look into it

**Comment by mrmelon54** [comment]
Issue resolved in v1.0.2
