### ISSUE TITLE
Original chestplate show when using CIT Resewn with custom textures

### ISSUE THREAD

**Issue by mrmelon54** [mrmelon54/armored-elytra-fabric#15]

**Comment by Julienraptor01** [comment]
I was about to report this issue but apparently you are already aware of it.
I just let you a comment to say thank you for this mod and be notified when you fix it. ❤️

**Comment by mrmelon54** [comment]
@Julienraptor01 important question: what mod are you using for CIT

**Comment by Julienraptor01** [comment]
> @Julienraptor01 important question: what mod are you using for CIT

CIT Resewn as it's the one compatible with OptiFine format.
I didn't tried Chime because it would mean i need to change the format of my CIT.

**Comment by mattyalanestock** [comment]
From what I could test, using CIT Resewn, the chestplate texture becomes completely dependent on what your worn helmet's CIT resolves to.

Examples:
- Using a default helmet will show the default chestplate.
- Wearing a named helmet with a full texture will draw that texture to both the helmet and chest slots.
- If your helmet CIT texture lacks pixels in the expected chestplate area, it'll effectively break the mod and show nothing.

Hopefully this helps!

**Comment by mrmelon54** [comment]
What mod are you using for CIT? I don't really want to support Optifine with Fabric but if I make a Forge version of my mod in the future I guess I should at least try supporting it.

**Comment by mattyalanestock** [comment]
CIT Resewn: https://www.curseforge.com/minecraft/mc-mods/cit-resewn

**Comment by mrmelon54** [comment]
Note to self: maybe copy armored elytra display name to chestplate in this part of the code?
https://github.com/MrMelon54/armored-elytra-fabric/blob/d1939d9c6d44e238fcc474d24df788da6e3d5aab/src/main/java/xyz/mrmelon54/ArmoredElytra/items/VanillaTweaksArmoredElytraItem.java#L74

might be better here
https://github.com/MrMelon54/armored-elytra-fabric/blob/d1939d9c6d44e238fcc474d24df788da6e3d5aab/src/main/java/xyz/mrmelon54/ArmoredElytra/mixin/MixinArmorFeatureRenderer.java#L52

**Comment by mrmelon54** [comment]
![image](https://github.com/MrMelon54/armored-elytra-fabric/assets/48031324/2f53234e-bd42-4056-a9a3-3c86ff88119b)
CIT Resewn appears to work in the 1.20 release, coming soon.

**Comment by mrmelon54** [comment]
This is fixed in the new architectury version... https://github.com/MrMelon54/armored_elytra
