### ISSUE TITLE
Loading the mod makes Essential GUI invisible

### ISSUE THREAD

**Issue by cymophic** [mrmelon54/armored-elytra-fabric#16]
Essential: https://www.curseforge.com/minecraft/mc-mods/essential-mod

With AEF Mod: 
![image](https://user-images.githubusercontent.com/97153344/182626755-6fb630e4-3bdd-48a7-92d6-d9626682989a.png)

Without:
![image](https://user-images.githubusercontent.com/97153344/182627362-942c349a-8413-48cf-b86d-0217f244b3af.png)

I couldn't find a reason why it does this. I hope me sharing this helps. Thanks

**Comment by mrmelon54** [comment]
Is this just with armored elytra and essential mod? Or is there other mods that could affect this? Looks like you have mod menu as well but it's not affecting it..

**Comment by cymophic** [comment]
I have a lot of mods (277 to be exact), but this invisibility error only occurred when I downloaded AEF.

**Comment by mrmelon54** [comment]
Can you try with just armored elytra and essential mod to see if its just specifically those two that cause this issue.. as armored elytra doesn't change anything to do with the title screen so idk why it wouldn't work properly?

**Comment by mrmelon54** [comment]
I have a new architectury based version of this mod.

If this issue still occurs, please make an issue on the new repository.

https://github.com/MrMelon54/armored_elytra
