### ISSUE TITLE
Occasional incompatibility with quilt

### ISSUE THREAD

**Issue by SilverAndro** [mrmelon54/armored-elytra-fabric#19]
[crash-2023-03-19_00.40.02-client.txt](https://github.com/MrMelon54/armored-elytra-fabric/files/11240696/crash-2023-03-19_00.40.02-client.txt)

Because armored elytra and QSL inject into the same place, theres a roughly 50/50 chance based on mod load order that, on quilt, will result in a crash. The issue is that your armor feature renderer may try to render elytra before quilt can save into a local variable what entity is being rendered (for its armor rendering API).

This can be remedied by either moving your rendering injection to be later in the method, or possibly by simply increasing the `priority` value, so that mixin sorts it to come after, although im less sure on that, you may have to lower the `priority` value instead.

**Comment by mrmelon54** [comment]
Unfortunately quilt is currently not supported, but I have plans to add support in the future and when I do so I will fix this.

**Comment by SilverAndro** [comment]
Awesome, thanks for the quick response!

**Comment by luximus-hunter** [comment]
Any updates on this?

**Comment by mrmelon54** [comment]
Quilt support is still planned, I'll probably release that along with the 1.20 updates.
I can always backport Quilt support to other versions.

**Comment by mrmelon54** [comment]
![image](https://github.com/MrMelon54/armored-elytra-fabric/assets/48031324/9aa42caa-594b-4612-8a70-6249af116fa9)
1.20 coming eventually, fixing this exact issue now lol

**Comment by mrmelon54** [comment]
Turns out the priority needs to be a smaller number for it to work
