### ISSUE TITLE
STDOUT is spammed

### ISSUE THREAD

**Issue by Beatso** [mrmelon54/armored-elytra-fabric#2]
with a netherite chestplate elytra equipped, the output logs are being filled with `[STDOUT]: returning item.minecraft.netherite_chestplate` which I believe to be from this mod. would it be possible to stop filling the logs with this?

**Comment by mrmelon54** [comment]
Just adding a note for myself so I can find it later:
TODO: remove https://github.com/MrMelon54/armored-elytra-fabric-1.16/blob/d8b9f31bdeee7de167c011bde6f1d5cdd7eee9a8/src/main/java/net/onpointcoding/armoredelytra/mixin/MixinLivingEntityChildren.java#L33

**Comment by Beatso** [comment]
i opened a PR (#3) if it helps :)
