### ISSUE TITLE
[suggesion] 1.19.3?

### ISSUE THREAD

**Issue by cootshk** [mrmelon54/armored-elytra-fabric#20]

**Comment by mrmelon54** [comment]
Can you try running the 1.19.2 version of the mod on 1.19.3. If it works then I'll just update modrinth to say it works.

**Comment by cootshk** [comment]
game loads, crashes when I press f5
crash report:
https://mclo.gs/yUkwDYP

**Comment by mrmelon54** [comment]
Done
