### ISSUE TITLE
[Request] Is 1.20.x Planned?

### ISSUE THREAD

**Issue by Avakining** [mrmelon54/armored-elytra-fabric#21]
Hi, is an update for 1.20/1.20.1 planned?

Thanks :)

**Comment by mrmelon54** [comment]
yep, there are screenshots in my discord of me testing out the armored elytra with armor trims

**Comment by mrmelon54** [comment]
New repo for forge/fabric/quilt version: https://github.com/MrMelon54/armored_elytra
