### ISSUE TITLE
Bug: Chestplate texture doesn't glow when enchanted

### ISSUE THREAD

**Issue by NeverEndingCycle** [mrmelon54/armored-elytra-fabric#8]
I'm not sure if this was something you intentionally avoided or if it was an oversight, but only the elytra texture has the enchanted glow if you enchant an armored elytra. I am using "Plated Elytras v 3.4 for MC 1.18.1" by Voodoo Beard. This is a problem for every armor type of armored elytra.

https://cdn.discordapp.com/attachments/482666390503817218/931516183054802974/unknown.png

**Comment by mrmelon54** [comment]
Hi which version of my mod are you using as I drastically changed how the rendering is done at one point?

**Comment by NeverEndingCycle** [comment]
I am using version 3.0 on minecraft 1.18.1.

**Comment by mrmelon54** [comment]
quick update from discord: I have implemented a fix but for plated elytra there is separate bug with the datapack that I have contacted the developer about
