### ISSUE TITLE
[Request] Support for chestplates from Advanced Netherite

### ISSUE THREAD

**Issue by chimericdream** [mrmelon54/armored-elytra-fabric#9]
Would it be possible to add support for the chestplates from the [Advanced Netherite mod](https://www.curseforge.com/minecraft/mc-mods/advanced-netherite-fabric)? I have modified the original Armored Elytra datapack from Vanilla Tweaks for the server I run, and I'd love to be able to show those variant textures as well.

Thanks!

**Comment by chimericdream** [comment]
Update: it looks like the armor renders correctly on the player model, so maybe just the item texture is what's needed? If so, I could probably use the custom model data for the item texture (if you think that's the better solution).

![image](https://user-images.githubusercontent.com/198075/151653084-1cad09a1-5fce-436a-8b7c-d7069433b508.png)

![image](https://user-images.githubusercontent.com/198075/151653089-320372e7-9a09-46dc-b54f-ff872679080a.png)

**Comment by mrmelon54** [comment]
Yep it is probably just those icons missing but maybe there is a smarter way to display them so I dont need to keep adding support for each armour mod?

**Comment by mrmelon54** [comment]
Oh and I'm gonna need the modified version of the datapack to actually be able to test my changes

**Comment by chimericdream** [comment]
Here's the modified datapack. Thanks for your help!

[armored-elytra.zip](https://github.com/MrMelon54/armored-elytra-fabric/files/7964357/armored-elytra.zip)

**Comment by mrmelon54** [comment]
Quick update I got the items to be detected as armored elytras now for the textures
![image](https://user-images.githubusercontent.com/48031324/151681593-424c30c1-deba-4aac-8bae-b73ccea339bd.png)

**Comment by mrmelon54** [comment]
Well that wasn't so difficult
![image](https://user-images.githubusercontent.com/48031324/151681674-946e609e-78f7-4c34-bc6a-abd9edff2008.png)

**Comment by mrmelon54** [comment]
this should be resolved with v3.0.2
